version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Ayesha-batool34/Ayesha-batool34.github.io"